[supervisord]
nodaemon=true
user=root
childlogdir=/var/log

[program:pulseaudio]
priority=1
autorestart=true
command=pulseaudio --daemonize=false

[program:spotifyd]
priority=5
autorestart=true
command=/usr/local/spotifyd/spotifyd --no-daemon --verbose

[program:musikbot]
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
autorestart=true
command=java --enable-native-access=ALL-UNNAMED -jar /usr/local/musikbot/musikbot.jar
